//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _728Meeting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Participant()
        {
            this.ParticipantEvent = new HashSet<ParticipantEvent>();
        }
    
        public string ParticipantId { get; set; }
        public string UserId { get; set; }
        public string MeetingInfo { get; set; }
        public string Notes { get; set; }
        public Nullable<byte> ExpertFee { get; set; }
        public Nullable<byte> TravelFee { get; set; }
        public string Subject { get; set; }
        public string ArrivalInfo { get; set; }
        public string DepartureInfo { get; set; }
        public string Contact { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> ViewedAt { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipantEvent> ParticipantEvent { get; set; }
    }
}
